version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: muzo-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: muzo
      MONGO_INITDB_ROOT_PASSWORD: muzo123
      MONGO_INITDB_DATABASE: muzo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 10s
      start_period: 30s

volumes:
  mongodb_data:
